version: '3.8'
services:
  web:
    build: ./movies_admin
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./movies_admin/:/usr/src/app/
      - .cache/pip-docker/:/root/.cache/pip
    ports:
      - 8000:8000
    env_file:
      - ./movies_admin/.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./movies_admin/config/db_schema.sql:/docker-entrypoint-initdb.d/1-init.sql
    env_file:
      - ./movies_admin/.env.dev

    ports:
      - 5432:5432

volumes:
  postgres_data: