version: '3.8'
services:
  web:
    build:
      context: ./movies_admin
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000
    expose:
      - 8000
    env_file:
      - ./movies_admin/.env.prod

  db:
    env_file:
      - ./movies_admin/.env.prod

    expose:
      - 5432

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  static_volume: