version: '3.8'
services:
  web:
    build:
      context: ./movies_admin
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./movies_admin/.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./movies_admin/config/db_schema.sql:/docker-entrypoint-initdb.d/1-init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=movies_database

    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: