version: '3.8'
services:
  web:
    build: ./movies_admin
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./movies_admin/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./movies_admin/.env.dev